apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
      - name: jobmanager
        image: sonoilmagopancione/flink:flinkv2
        args:
        - jobmanager
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 6125
          name: query
        - containerPort: 8081
          name: ui
        resources:
            requests:
              cpu: 1000m
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager
        lifecycle:
          postStart:
            exec:
              command: ['/bin/sh','-c','crond -l 2 -b']
